theme = "tokyonight_deep"
client_id = "c47089f9ef7847548f16447677f6d117"
playback_format = """
  {status} {track}
  {artists} • {album}
  {metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = ""
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
enable_cover_image_cache = true
enable_media_control = true
seek_duration_secs = 5
enable_streaming = "DaemonOnly"
cover_img_scale = 1.2

[layout]
playback_window_position = "Top"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
autoplay = false
