mouse_support: true
invidious_instance: https://invidious.fdn.fr
write_config: Try
allow_unicode: true
message_bar_default: "Ready"
images: Sixels
refresh_after_modifying_search_filters: true
syncing:
  download_images: true
  sync_channel_info: true
  sync_channel_cooldown_secs: 86400
  sync_videos_cooldown_secs: 600
limits:
  watch_history: 100
  search_history: 100
  commands_history: 100
textbar_scroll_behaviour: Word
image_index: 1
provider: YouTube
search_provider: RustyPipe
shell: sh
legacy_input_handling: false
env:
  video-player: mpv
  download-path: ~/downloads/%(title)s-%(id)s.%(ext)s
  terminal-emulator: wezterm start --
  youtube-downloader: yt-dlp
  save-path: ~/.local/share/youtube-tui/saved/
  browser: xdg-open
