%YAML 1.3
---
- Rule:
  - Key: [Lock PC, pressed]
  - KeyPress:
    - [Super_L, Control_L, Alt_L, Shift_L]
    - depress
  - KeyPress:
    - acute
    - click
  - KeyPress:
    - [Super_L, Shift_L, Control_L, Alt_L]
    - release
...
