[[themes]]
name = "tokyonight_deep"

[themes.palette]
background      = "#010111"
foreground      = "#ffffff"
black           = "#363b54"
red             = "#f7768e"
green           = "#41a6b5"
yellow          = "#e6c100"
blue            = "#7aa2f7"
magenta         = "#bb9af7"
cyan            = "#7dcfff"
white           = "#b9bdcc"
bright_black    = "#454c6d"
bright_red      = "#ff5f8f"
bright_green    = "#00ffbb"
bright_yellow   = "#ffee00"
bright_blue     = "#82aaff"
bright_magenta  = "#d5a6ff"
bright_cyan     = "#8bffff"
bright_white    = "#d0d6e3"

[themes.component_style]
block_title = { fg = "Magenta" }
border = { fg = "BrightBlack" }
playback_status = { fg = "Cyan", modifiers = ["Bold"] }
playback_track = { fg = "BrightYellow", modifiers = ["Bold"] }
playback_artists = { fg = "BrightCyan", modifiers = ["Bold"] }
playback_album = { fg = "Blue" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg = "BrightBlack", fg = "Green" }
playback_progress_bar_unfilled = { bg = "BrightBlack", fg = "BrightBlack" }
current_playing = { fg = "BrightCyan", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
selection = { fg = "BrightCyan", bg = "BrightBlack", modifiers = ["Bold"] }
secondary_row = { fg = "BrightBlack" }
like = { fg = "Red" }
lyrics_played = { fg = "BrightBlack", modifiers = ["Dim"] }

