browser_cookies:
  auto_import: false
  browser: firefox
  sites:
  - anontransfer.com
  - anysex.com
  - bandcamp.com
  - beeg.com
  - bestprettygirl.com
  - boards.4chan.org
  - bunkr-albums.io
  - bunkr.site
  - buzzheavier.com
  - catbox.moe
  - celebforum.to
  - cloudflarestream.com
  - comics.8muses.com
  - coomer.st
  - cyberdrop.cr
  - cyberfile.me
  - desivideo.net
  - dirtyship.com
  - disk.yandex.com.tr
  - doodstream.com
  - drive.google.com
  - e-hentai.org
  - e621.net
  - efukt.com
  - erome.fan
  - everia.club
  - f95zone.to
  - fapello.su
  - fileditchfiles.me
  - files.vc
  - flugelanime.com
  - forum.allporncomix.com
  - forums.plex.tv
  - forums.socialmediagirls.com
  - fsiblog5.com
  - fuckingfast.co
  - fuxxx.com
  - gofile.io
  - hclips.com
  - hdzog.com
  - hianime.to
  - hitomi.la
  - hotleak.vip
  - hotleaks.tv
  - hotmovs.com
  - hotpic.cc
  - ibb.co
  - iceyfile.com
  - imagepond.net
  - imgbox.com
  - imglike.com
  - imgur.com
  - imx.to
  - influencerbitches.com
  - inporn.com
  - jpg6.su
  - kemono.cr
  - koofr.eu
  - leakedmodels.com
  - leakedzone.com
  - lolpol.com
  - luxuretv.com
  - masahub.com
  - mega.nz
  - megacloud.blog
  - members.luscious.net
  - missav.ws
  - mixdrop.sb
  - motherless.com
  - nekohouse.su
  - nhentai.net
  - noodlemagazine.com
  - nsfw.xxx
  - nudostar.com
  - nudostar.tv
  - ok.ru
  - omegascans.org
  - onedrive.com
  - photos.google.com
  - pimpandhost.com
  - pimpbunny.com
  - pixeldrain.com
  - pixhost.to
  - pkmncards.com
  - pmvhaven.com
  - pornpics.com
  - pornzog.com
  - postimg.cc
  - ranoz.gg
  - realbooru.com
  - rule34.xxx
  - rule34.xyz
  - rule34vault.com
  - rule34video.com
  - rumble.com
  - safe.soul.lol
  - scrolller.com
  - send.now
  - sendvid.com
  - sex.com
  - simpcity.cr
  - spankbang.com
  - streamable.com
  - streamtape.com
  - thisvid.com
  - thothub.to
  - titsintops.com
  - toonily.com
  - transfer.it
  - transflix.net
  - tubepornclassic.com
  - turbovid.cr
  - twimg.com
  - txxx.com
  - upornia.com
  - vipergirls.to
  - vipr.im
  - vjav.com
  - voe.sx
  - voyeurhit.com
  - vxxx.com
  - wetransfer.com
  - www.archivebate.store
  - www.ashemaletube.com
  - www.bellazon.com
  - www.box.com
  - www.camwhores.tv
  - www.dropbox.com
  - www.eporner.com
  - www.erome.com
  - www.girlsreleased.com
  - www.imagebam.com
  - www.incestflix.com
  - www.mediafire.com
  - www.pcloud.com
  - www.pornhub.com
  - www.porntrex.com
  - www.reddit.com
  - www.redgifs.com
  - www.rootz.so
  - www.tiktok.com
  - www.tnaflix.com
  - www.tokyomotion.net
  - www.tranny.one
  - www.twitch.tv
  - www.twpornstars.com
  - www.xasiat.com
  - www.xvideos.com
  - www.youjizz.com
  - xbunker.nu
  - xbunkr.com
  - xgroovy.com
  - xhamster.com
  - xmilf.com
  - xxxbunker.com
download_options:
  block_download_sub_folders: false
  disable_download_attempt_limit: false
  disable_file_timestamps: false
  include_album_id_in_folder_name: false
  include_thread_id_in_folder_name: false
  maximum_number_of_children: []
  maximum_thread_depth: 0
  maximum_thread_folder_depth: null
  remove_domains_from_folder_names: false
  remove_generated_id_from_filenames: false
  scrape_single_forum_post: false
  separate_posts: false
  separate_posts_format: '{default}'
  skip_download_mark_completed: false
  skip_referer_seen_before: false
dupe_cleanup_options:
  add_md5_hash: false
  add_sha256_hash: false
  auto_dedupe: true
  hashing: IN_PLACE
  send_deleted_to_trash: true
file_size_limits:
  maximum_image_size: 0B
  maximum_other_size: 0B
  maximum_video_size: 0B
  minimum_image_size: 0B
  minimum_other_size: 0B
  minimum_video_size: 0B
files:
  download_folder: .
  dump_json: false
  input_file: ~/.config/cyberdrop-dl/URLs.txt
  save_pages_html: false
ignore_options:
  exclude_after: null
  exclude_audio: false
  exclude_before: null
  exclude_files_with_no_extension: true
  exclude_images: false
  exclude_other: false
  exclude_videos: false
  filename_regex_filter: null
  ignore_coomer_ads: false
  ignore_coomer_post_content: true
  only_hosts: []
  skip_hosts: []
logs:
  download_error_urls: Download_Error_URLs.csv
  last_forum_post: Last_Scraped_Forum_Posts.csv
  log_folder: /tmp/cyberdrop-dl-logs
  log_line_width: 240
  logs_expire_after: null
  main_log: downloader.log
  rotate_logs: false
  scrape_error_urls: Scrape_Error_URLs.csv
  unsupported_urls: Unsupported_URLs.csv
  webhook: null
media_duration_limits:
  maximum_audio_duration: &id001 PT0S
  maximum_video_duration: *id001
  minimum_audio_duration: *id001
  minimum_video_duration: *id001
runtime_options:
  console_log_level: 40
  deep_scrape: false
  delete_partial_files: false
  ignore_history: false
  jdownloader_autostart: false
  jdownloader_download_dir: null
  jdownloader_whitelist: []
  log_level: 40
  send_unsupported_to_jdownloader: false
  skip_check_for_empty_folders: false
  skip_check_for_partial_files: false
  slow_download_speed: 0B
  update_last_forum_post: true
sorting:
  scan_folder: null
  sort_downloads: false
  sort_folder: /tmp/cyberdrop-dl-sorted
  sort_incrementer_format: ({i})
  sorted_audio: '{sort_dir}/{base_dir}/Audio/{filename}{ext}'
  sorted_image: '{sort_dir}/{base_dir}/Images/{filename}{ext}'
  sorted_other: '{sort_dir}/{base_dir}/Other/{filename}{ext}'
  sorted_video: '{sort_dir}/{base_dir}/Videos/{filename}{ext}'
